server:
  port: 8080

spring:
  webflux:
    base-path: /api/v1

  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}

  flyway:
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations: ${FLYWAY_LOCATIONS}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    url: ${FLYWAY_URL}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_secret: ${CLOUDINARY_API_SECRET}
  api_key: ${CLOUDINARY_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

