server:
  port: ${PORT:8080}

spring:
  webflux:
    base-path: /api/v1

  r2dbc:
    url: r2dbc:postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}?sslMode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}

  flyway:
    user: ${PGUSER}
    password: ${PGPASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_secret: ${CLOUDINARY_API_SECRET}
  api_key: ${CLOUDINARY_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
